/* Generated By:JJTree: Do not edit this line. ASTAbsSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAbsSlash extends SimpleNode {
  public ASTAbsSlash(int id) {
    super(id);
  }

  public ASTAbsSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e92ecc41f632549e5063fbae44598f90 (do not edit this line) */
