/* Generated By:JJTree: Do not edit this line. ASTAbsDSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTAbsDSlash extends SimpleNode {
  public ASTAbsDSlash(int id) {
    super(id);
  }

  public ASTAbsDSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=79f05bd2cf4bf1ceb0867d5855a99984 (do not edit this line) */
