/* Generated By:JJTree: Do not edit this line. ASTCondEmpty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondEmpty extends SimpleNode {
  public ASTCondEmpty(int id) {
    super(id);
  }

  public ASTCondEmpty(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=9c0da9ba7789163eeb3fe8d0f6e71a16 (do not edit this line) */
