/* Generated By:JJTree: Do not edit this line. ASTCondAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondAnd extends SimpleNode {
  public ASTCondAnd(int id) {
    super(id);
  }

  public ASTCondAnd(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=da15a07e93906a97172f6a0cc4a9b478 (do not edit this line) */
