/* Generated By:JJTree: Do not edit this line. ASTCondSome.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondSome extends SimpleNode {
  public ASTCondSome(int id) {
    super(id);
  }

  public ASTCondSome(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=47bf4f1e17ab562c8b42e7e51b0aa015 (do not edit this line) */
