/* Generated By:JJTree: Do not edit this line. ASTCondEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondEq extends SimpleNode {
  public ASTCondEq(int id) {
    super(XQueryParserTreeConstants.JJTCONDEQ);
  }

  public ASTCondEq(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9835196a8d4e3a1cd91d4938d304fe68 (do not edit this line) */
