/* Generated By:JJTree: Do not edit this line. ASTFilterParen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterParen extends SimpleNode {
  public ASTFilterParen(int id) {
    super(id);
  }

  public ASTFilterParen(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b83be2c0833f607252d7da117b9369fe (do not edit this line) */
