/* Generated By:JJTree: Do not edit this line. ASTFilterNot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterNot extends SimpleNode {
  public ASTFilterNot(int id) {
    super(id);
  }

  public ASTFilterNot(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e98e437557db9b81a448e36c1495cfa3 (do not edit this line) */
