/* Generated By:JJTree: Do not edit this line. ASTIn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTIn extends SimpleNode {
  public ASTIn(int id) {
    super(id);
  }

  public ASTIn(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a000d23bdde7ac84d4d9100f47805a44 (do not edit this line) */
