/* Generated By:JJTree: Do not edit this line. ASTLetClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTLetClause extends SimpleNode {
  public ASTLetClause(int id) {
    super(id);
  }

  public ASTLetClause(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=707a66a8b43f934bd5aa04cd0939c096 (do not edit this line) */
