/* Generated By:JJTree: Do not edit this line. ASTLX.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTLX extends SimpleNode {
  public ASTLX(int id) {
    super(id);
  }

  public ASTLX(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5ccd12c1b3777050ee30d9e28753ca19 (do not edit this line) */
