/* Generated By:JJTree: Do not edit this line. ASTNewtag.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNewtag extends SimpleNode {

  public String tagName;

  public ASTNewtag(int id) {
    super(id);
  }

  public ASTNewtag(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c590f8a39e2a88f8942dc9f4c9e17805 (do not edit this line) */
