/* Generated By:JJTree: Do not edit this line. ASTReturnClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTReturnClause extends SimpleNode {
  public ASTReturnClause(int id) {
    super(id);
  }

  public ASTReturnClause(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=011fee5cc60d69e35ba52017895dd103 (do not edit this line) */
