/* Generated By:JJTree: Do not edit this line. ASTReturnClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTReturnClause extends SimpleNode {
  public ASTReturnClause(int id) {
    super(id);
  }

  public ASTReturnClause(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=749b4495cc56f4be522c945313e178e4 (do not edit this line) */
