/* Generated By:JJTree: Do not edit this line. ASTRelDSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRelDSlash extends SimpleNode {
  public ASTRelDSlash(int id) {
    super(id);
  }

  public ASTRelDSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a54fbc46165f7f8a1118c34197e9d0aa (do not edit this line) */
