/* Generated By:JJTree: Do not edit this line. ASTRelFilter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRelFilter extends SimpleNode {
  public ASTRelFilter(int id) {
    super(id);
  }

  public ASTRelFilter(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f0ce0f5ee749c5ec7fe47a944ee18bdc (do not edit this line) */
