/* Generated By:JJTree: Do not edit this line. ASTRelSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRelSlash extends SimpleNode {
  public ASTRelSlash(int id) {
    super(id);
  }

  public ASTRelSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=f5a321b5e12637bb39ac807d68d08d75 (do not edit this line) */
