/* Generated By:JJTree: Do not edit this line. ASTTagName.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTTagName extends SimpleNode {

  public String tagName;

  public ASTTagName(int id) {
    super(id);
  }

  public ASTTagName(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4a98daee848d71228de94760a54f5e4e (do not edit this line) */
