/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTVar extends SimpleNode {

  public String varName;

  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=23f867da33eb815c78ce6e524a68e9c9 (do not edit this line) */
