/* Generated By:JJTree: Do not edit this line. ASTVar.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTVar extends SimpleNode {

  public String varName;

  public ASTVar(String varName) {
  	super(0);
  	this.varName = varName;
  }
  
  public ASTVar(int id) {
    super(id);
  }

  public ASTVar(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=a2cf100870dd4ea85ead33c8b318fd20 (do not edit this line) */
