/* Generated By:JavaCC: Do not edit this line. XQueryParserTreeConstants.java Version 5.0 */
package parser;

public interface XQueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDOC = 2;
  public int JJTABSSLASH = 3;
  public int JJTABSDSLASH = 4;
  public int JJTRELSLASH = 5;
  public int JJTRELDSLASH = 6;
  public int JJTRELFILTER = 7;
  public int JJTRELCOMMA = 8;
  public int JJTSTAR = 9;
  public int JJTDOT = 10;
  public int JJTDDOT = 11;
  public int JJTTEXT = 12;
  public int JJTPAREN = 13;
  public int JJTTAGNAME = 14;
  public int JJTFILTERAND = 15;
  public int JJTFILTEROR = 16;
  public int JJTFILTEREQ = 17;
  public int JJTFILTERIS = 18;
  public int JJTFILTERRELPATH = 19;
  public int JJTFILTERPAREN = 20;
  public int JJTFILTERNOT = 21;
  public int JJTFORCLAUSE = 22;
  public int JJTIN = 23;
  public int JJTLETCLAUSE = 24;
  public int JJTASSIGN = 25;
  public int JJTWHERECLAUSE = 26;
  public int JJTRETURNCLAUSE = 27;
  public int JJTCONDAND = 28;
  public int JJTCONDOR = 29;
  public int JJTCONDEQ = 30;
  public int JJTCONDIS = 31;
  public int JJTCONDEMPTY = 32;
  public int JJTCONDSOME = 33;
  public int JJTVAR = 34;
  public int JJTXQUERYCOMMA = 35;
  public int JJTXQUERYSLASH = 36;
  public int JJTSTRING = 37;
  public int JJTNEWTAG = 38;
  public int JJTFLWR = 39;
  public int JJTLX = 40;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Doc",
    "AbsSlash",
    "AbsDSlash",
    "RelSlash",
    "RelDSlash",
    "RelFilter",
    "RelComma",
    "Star",
    "Dot",
    "Ddot",
    "Text",
    "Paren",
    "TagName",
    "FilterAnd",
    "FilterOr",
    "FilterEq",
    "FilterIs",
    "FilterRelPath",
    "FilterParen",
    "FilterNot",
    "ForClause",
    "In",
    "LetClause",
    "Assign",
    "WhereClause",
    "ReturnClause",
    "CondAnd",
    "CondOr",
    "CondEq",
    "CondIs",
    "CondEmpty",
    "CondSome",
    "Var",
    "XQueryComma",
    "XQuerySlash",
    "String",
    "Newtag",
    "FLWR",
    "LX",
  };
}
/* JavaCC - OriginalChecksum=e91aa2610d8bbe344416861f64460f9f (do not edit this line) */
