/* Generated By:JJTree: Do not edit this line. ASTCondEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondEq extends SimpleNode {
  public ASTCondEq(int id) {
    super(id);
  }

  public ASTCondEq(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=e20b428934077fd699ea46ec7d920fbd (do not edit this line) */
