/* Generated By:JJTree: Do not edit this line. ASTCondIs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondIs extends SimpleNode {
  public ASTCondIs(int id) {
    super(id);
  }

  public ASTCondIs(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=358c95c2281e762925af7293f80e551a (do not edit this line) */
