/* Generated By:JJTree: Do not edit this line. ASTCondOr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTCondOr extends SimpleNode {
  public ASTCondOr(int id) {
    super(id);
  }

  public ASTCondOr(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c832e599e9e010bd2108e60e5445fe2f (do not edit this line) */
