/* Generated By:JJTree: Do not edit this line. ASTDot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDot extends SimpleNode {
  public ASTDot(int id) {
    super(id);
  }

  public ASTDot(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6a166f746c9ea2010f431d8d0612fdcf (do not edit this line) */
