/* Generated By:JJTree: Do not edit this line. ASTDoc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDoc extends SimpleNode {

  public String fileName;

  public ASTDoc(int id) {
    super(id);
  }

  public ASTDoc(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=789ac1f04838780bf069fbf6b0ffe83a (do not edit this line) */
