/* Generated By:JJTree: Do not edit this line. ASTDoc.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTDoc extends SimpleNode {

  public String fileName;

  public ASTDoc(int id) {
    super(id);
  }

  public ASTDoc(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2c4062b4a723c81021f5c5d7eddbbb53 (do not edit this line) */
