/* Generated By:JJTree: Do not edit this line. ASTFilterRelPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterRelPath extends SimpleNode {
  public ASTFilterRelPath(int id) {
    super(id);
  }

  public ASTFilterRelPath(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8f4b7e7b6d604c44baffe920270046c5 (do not edit this line) */
