/* Generated By:JJTree: Do not edit this line. ASTForClause.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTForClause extends SimpleNode {
  public ASTForClause(int id) {
    super(id);
  }

  public ASTForClause(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=1574fa945e28af229c767f62ac5ea671 (do not edit this line) */
