/* Generated By:JJTree: Do not edit this line. ASTFLWR.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFLWR extends SimpleNode {
  public ASTFLWR(int id) {
    super(id);
  }

  public ASTFLWR(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=7b7ef2b5ef6daaec1cf7fe5febea936a (do not edit this line) */
