/* Generated By:JJTree: Do not edit this line. ASTFilterEq.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterEq extends SimpleNode {
  public ASTFilterEq(int id) {
    super(id);
  }

  public ASTFilterEq(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=efb43245d3c3474212c6384661e35b63 (do not edit this line) */
