/* Generated By:JJTree: Do not edit this line. ASTFilterIs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterIs extends SimpleNode {
  public ASTFilterIs(int id) {
    super(id);
  }

  public ASTFilterIs(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6db4d985156507f053d13fb9395c2e66 (do not edit this line) */
