/* Generated By:JJTree: Do not edit this line. ASTFilterAnd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTFilterAnd extends SimpleNode {
  public ASTFilterAnd(int id) {
    super(id);
  }

  public ASTFilterAnd(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=4cffca48cb76c4e8dbcc5081107ce875 (do not edit this line) */
