/* Generated By:JJTree: Do not edit this line. ASTJoinList.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTJoinList extends SimpleNode {
  public ASTJoinList(int id) {
    super(XQueryParserTreeConstants.JJTJOINLIST);
  }

  public ASTJoinList(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9538f7c0795a24cdc2f8bb54635ae6c7 (do not edit this line) */
