/* Generated By:JJTree: Do not edit this line. ASTNewtag.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTNewtag extends SimpleNode {

  public String tagName;

  public ASTNewtag(String tagName) {
  	super(0);
  	this.tagName = tagName;
  }
  
  public ASTNewtag(int id) {
    super(id);
  }

  public ASTNewtag(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=465e202cee66f179097c6d96a16a5a32 (do not edit this line) */
