/* Generated By:JJTree: Do not edit this line. ASTParen.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTParen extends SimpleNode {
  public ASTParen(int id) {
    super(id);
  }

  public ASTParen(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=dba2873bb1c2e8936371cda95a027ee8 (do not edit this line) */
