/* Generated By:JJTree: Do not edit this line. ASTRelComma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTRelComma extends SimpleNode {
  public ASTRelComma(int id) {
    super(id);
  }

  public ASTRelComma(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=5db39b68180d4e71238ada285a2bd0ae (do not edit this line) */
