/* Generated By:JJTree: Do not edit this line. ASTSlash.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTSlash extends SimpleNode {
  public ASTSlash(int id) {
    super(id);
  }

  public ASTSlash(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b592847e1ba3fea66bfeb1c569b3b134 (do not edit this line) */
