/* Generated By:JJTree: Do not edit this line. ASTString.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTString extends SimpleNode {
  
  public String strName;

  public ASTString(int id) {
    super(id);
  }

  public ASTString(XQueryParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d05a19e9d43d268e32f7159e996b003a (do not edit this line) */
