/* Generated By:JJTree: Do not edit this line. ASTXQueryComma.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package parser;

public
class ASTXQueryComma extends SimpleNode {
  public ASTXQueryComma(int id) {
    super(XQueryParserTreeConstants.JJTXQUERYCOMMA);
  }

  public ASTXQueryComma(XQueryParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(XQueryParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02fb28d17831475b035cb33e19718c31 (do not edit this line) */
