/* Generated By:JavaCC: Do not edit this line. XQueryParserTreeConstants.java Version 5.0 */
package parser;

public interface XQueryParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTDOC = 2;
  public int JJTABSSLASH = 3;
  public int JJTABSDSLASH = 4;
  public int JJTRELSLASH = 5;
  public int JJTRELDSLASH = 6;
  public int JJTRELFILTER = 7;
  public int JJTRELCOMMA = 8;
  public int JJTSTAR = 9;
  public int JJTDOT = 10;
  public int JJTDDOT = 11;
  public int JJTTEXT = 12;
  public int JJTPAREN = 13;
  public int JJTFILTERAND = 14;
  public int JJTFILTEROR = 15;
  public int JJTFILTEREQ = 16;
  public int JJTFILTERIS = 17;
  public int JJTFILTERRELPATH = 18;
  public int JJTFILTERPAREN = 19;
  public int JJTFILTERNOT = 20;
  public int JJTFORCLAUSE = 21;
  public int JJTIN = 22;
  public int JJTLETCLAUSE = 23;
  public int JJTASSIGN = 24;
  public int JJTWHERECLAUSE = 25;
  public int JJTRETURNCLAUSE = 26;
  public int JJTCONDAND = 27;
  public int JJTCONDOR = 28;
  public int JJTCONDEQ = 29;
  public int JJTCONDIS = 30;
  public int JJTCONDEMPTY = 31;
  public int JJTCONDSOME = 32;
  public int JJTVAR = 33;
  public int JJTXQUERYCOMMA = 34;
  public int JJTXQUERYSLASH = 35;
  public int JJTSTRING = 36;
  public int JJTNEWTAG = 37;
  public int JJTJOIN = 38;
  public int JJTFLWR = 39;
  public int JJTLX = 40;
  public int JJTJOINLIST = 41;
  public int JJTTAGNAME = 42;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Doc",
    "AbsSlash",
    "AbsDSlash",
    "RelSlash",
    "RelDSlash",
    "RelFilter",
    "RelComma",
    "Star",
    "Dot",
    "Ddot",
    "Text",
    "Paren",
    "FilterAnd",
    "FilterOr",
    "FilterEq",
    "FilterIs",
    "FilterRelPath",
    "FilterParen",
    "FilterNot",
    "ForClause",
    "In",
    "LetClause",
    "Assign",
    "WhereClause",
    "ReturnClause",
    "CondAnd",
    "CondOr",
    "CondEq",
    "CondIs",
    "CondEmpty",
    "CondSome",
    "Var",
    "XQueryComma",
    "XQuerySlash",
    "String",
    "Newtag",
    "Join",
    "FLWR",
    "LX",
    "JoinList",
    "TagName",
  };
}
/* JavaCC - OriginalChecksum=37b2c0437bc0a582ea06aed834c517ce (do not edit this line) */
